import { Card, CardContent } from "@/components/ui/card";
import { 
  Bluetooth, 
  QrCode, 
  Clock, 
  Volume2, 
  BarChart3, 
  Shield,
  Smartphone,
  Users,
  Database,
  Settings
} from "lucide-react";

const features = [
  {
    icon: Bluetooth,
    title: "Bluetooth-Based & QR Attendance",
    description: "Students can check in using BLE beacons installed in classrooms or scan QR codes generated by instructors."
  },
  {
    icon: Clock,
    title: "Timestamped Entry & Exit Logs",
    description: "Real-time logging of student presence, validated by geolocation and session windows."
  },
  {
    icon: BarChart3,
    title: "Real-Time Dashboards",
    description: "Live attendance tracking, performance metrics, and analytics for admin, lecturers, and management."
  },
  {
    icon: Volume2,
    title: "Reduced Class Disruptions",
    description: "No more roll calls—attendance happens silently and securely in the background."
  },
  {
    icon: Smartphone,
    title: "Mobile-First Design",
    description: "Native mobile apps for students and web dashboards for administrators and lecturers."
  },
  {
    icon: Shield,
    title: "Security-Centric",
    description: "Device binding, location validation, and encrypted data to prevent proxy attendance."
  }
];

const systemFeatures = [
  {
    icon: Settings,
    title: "Smart Attendance System",
    description: "BLE beacons + QR codes with 2-minute presence validation and secure device-binding to prevent fraud."
  },
  {
    icon: Users,
    title: "Role-Based Platform",
    description: "Comprehensive access control for students, lecturers, admins, and system administrators."
  },
  {
    icon: BarChart3,
    title: "Data-Driven Reporting",
    description: "Exportable reports, attendance heatmaps, and anomaly detection for informed decision-making."
  },
  {
    icon: Database,
    title: "Beacon & Course Management",
    description: "Complete beacon assignment, session scheduling, and signal testing capabilities."
  }
];

const FeaturesSection = () => {
  return (
    <section id="features" className="py-20 bg-gradient-subtle">
      <div className="container">
        {/* Key Features */}
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Key Features & Benefits</h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Everything you need for modern, efficient attendance tracking in universities.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-20">
          {features.map((feature, index) => {
            const IconComponent = feature.icon;
            return (
              <Card key={index} className="border-primary/10 hover:shadow-elegant transition-smooth group">
                <CardContent className="p-6">
                  <div className="w-12 h-12 bg-brand-light rounded-full flex items-center justify-center mb-4 group-hover:scale-110 transition-smooth">
                    <IconComponent className="h-6 w-6 text-primary" />
                  </div>
                  <div className="flex items-start space-x-1 mb-2">
                    <div className="w-4 h-4 rounded-full bg-primary flex-shrink-0 mt-1 flex items-center justify-center">
                      <div className="w-2 h-2 rounded-full bg-white"></div>
                    </div>
                    <h3 className="text-lg font-semibold">{feature.title}</h3>
                  </div>
                  <p className="text-muted-foreground leading-relaxed">{feature.description}</p>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* System Features */}
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">System Features</h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Advanced capabilities for tech-savvy users and institutions.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {systemFeatures.map((feature, index) => {
            const IconComponent = feature.icon;
            return (
              <Card key={index} className="border-primary/10 hover:shadow-elegant transition-smooth group">
                <CardContent className="p-8">
                  <div className="flex items-start space-x-4">
                    <div className="w-12 h-12 bg-brand-light rounded-full flex items-center justify-center flex-shrink-0 group-hover:scale-110 transition-smooth">
                      <IconComponent className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                      <p className="text-muted-foreground leading-relaxed">{feature.description}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;